### PR TITLE
Create stand alone can module build

### PR DESCRIPTION
**Pull request by ben-farnham**
This pull request is almost entirely concerned with build modifications: The CanModule can now: 
* build as an optional module of any quasar server
* build as a shared library (windows and linux) with LogIt built internally into the library.
* build as a shared library (windows and linux) with LogIt linked from an external location

I spent quite a bit of time on the README.md too - the build instructions (and unit test execution instructions) are described there.

### CODE REVIEW

**Comment by ben-farnham** [comment]
> doesn't work in standalone + out-of-source mode
Fixed (following the steps mkdir build, cd build and cmake ...etc...

> I got a shared library (.so) but I didn't request one via CMake flags 
True - currently there is no support for the stand-alone build creating a static library; only a shared library. I vote that **this** feature's pull-request merges as-is: stand-alone builds a shared library. Adding the option to build shared/static is another feature, another branch & pull request.

**Comment by ben-farnham** [comment]
Ah, I see. OK, will clean that up. Thanks for spotting it.

**Comment by ben-farnham** [comment]
Done. Ready for merge to master I guess?

**Comment by pnikiel** [comment]
Yes OK for me.

**Comment by ben-farnham** [comment]
Merged. Thanks for the review Piotr.

**Pull request merged**
